name: deploy my lambda function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out my lambda function code
        uses: actions/checkout@v3
      - name: setup python v3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install python libraries
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create zip bundle
        run: |
            cd function
            zip -r python_build-${{ github.run_number }}.zip * .*
      - name: archive python bundle
        uses: actions/upload-artifact@v3
        with:
          name: python_build
          path: python_build-${{ github.run_number }}.zip