name: deploy my lambda function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out my lambda function code
        uses: actions/checkout@v3
      - name: setup python v3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: install python libraries
        run: |
            cd functions
            python -m pip install --upgrade pip
            if [-f requirements.txt ]; then pip install -r requirements.txt -t .; fi