name: deploy my lambda function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out my lambda function code
        uses: actions/checkout@v3

      - name: setup python v3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python libraries
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi

      - name: Create zip bundle
        run: |
            cd function
            zip -r python_build-${{ github.run_number }}.zip * .*

      - name: archive python bundle
        uses: actions/upload-artifact@v3
        with:
          path: python_build-${{ github.run_number }}.zip


  upload_artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: zipped-bundle

      - name: configure-awscli-v2
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: upload artifact aws s3
        run: aws s3 cp python_build-${{ github.run_number }}.zip s3://jayasekhar.tech/python_build-${{ github.run_number }}.zip
