name: deploy my lambda function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out my lambda function code
        uses: actions/checkout@v3
      - name: setup python v3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install python libraries
        run: |
            cd functions
            python -m pip install --upgrade pip
            pip install -r requirements.txt -t .