name: deploy my lambda function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out my lambda function code
        uses: actions/checkout@v3

      - name: setup python v3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python libraries
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi

      - name: Create zip bundle
        run: |
            cd function
            zip -r ../python_build-${{ github.run_number }}.zip * .*

      - name: configure-awscli-v2
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: upload artifact aws s3
        run: aws s3 cp python_build-${{ github.run_number }}.zip s3://jayasekhar.tech/python_build-${{ github.run_number }}.zip


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: configure-awscli-v2
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Create Test function
        run: |
            aws lambda create-function --function-name test-function \
              --code S3Bucket=jayasekhar.tech,S3Key=python_build-${{ github.run_number }}.zip \
              --handler lambda_function.lambda_handler --runtime python3.9 \
              --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/my-lambda-func

      - name: Sleep for 30seconds
        run: sleep 30
        if: ${{ always() }}
      - name: Destroy test lambda function
        run: aws lambda delete-function test-function


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: configure-awscli-v2
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: update lambda function code
        run: |
            aws lambda update-function-code \
              --function-name my-py-lambda-function \
              --s3-bucket jayasekhar.tech \
              --s3-key python_build-${{ github.run_number }}.zip \
              --publish
